# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Proj
version=6.0.0-SNAPSHOT
group=com.github.anopensaucedev
java_version=21

# Mod Properties
mod_name=FasterRandom
mod_author=AnOpenSauceDev
mod_id=fasterrandom
license=Apache-2.0
credits=Steveplays28,unilock,four4tReS,404
description=Makes your game randomly faster!

# Minecraft Properties
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Fabric
fabric_version=0.119.2+1.21.4
fabric_loader_version=0.16.10
fabric_game_version_range=>=1.21.4

# Forge
forge_version=54.1.0
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=21.4.136
neoforge_loader_version_range=[4,)
neoforge_version_range=[21,)
