modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/AnOpenSauceDev/FastRandom/issues" #optional

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL = "https://api.modrinth.com/updates/faster-random/forge_updates.json"
displayURL = "https://modrinth.com/project/faster-random"
logoFile="assets/fasterrandom/icon.png"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
